# Generated by Django 3.0.8 on 2020-07-12 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InterPatentCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10)),
                ('firstcode', models.CharField(max_length=10)),
                ('seccode', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='LawStatusEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='PatentAuthor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='PatentCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Patent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pid', models.CharField(max_length=64)),
                ('an', models.CharField(max_length=20)),
                ('pn', models.CharField(max_length=20)),
                ('ti', models.CharField(max_length=100)),
                ('ls', models.CharField(max_length=5)),
                ('ad', models.DateField()),
                ('pd', models.DateField()),
                ('ab', models.TextField()),
                ('clm', models.TextField()),
                ('cdn', models.ManyToManyField(related_name='cdnpatent', to='importdata.PatentCode')),
                ('ctn', models.ManyToManyField(related_name='ctnpatent', to='importdata.PatentCode')),
                ('ipc', models.ManyToManyField(to='importdata.InterPatentCode')),
                ('lse', models.ManyToManyField(to='importdata.LawStatusEvent')),
                ('pa', models.ManyToManyField(to='importdata.PatentAuthor')),
            ],
        ),
    ]
